version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: barbarshop-postgres
    enviroment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgres/data

volumes:
  .postgres.data:
